name: 'Disallow Concurrent Runs'
description: 'A GitHub Action for disallowing concurrent workflow runs'
inputs:
  token:
    description: 'The GitHub token that''s intended for actions'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
